name: Killakoi
favicon: null
layout_spectrum: 0.97988
typography_spectrum: 0.93964
title: Killakoi Band
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f0c8a5'
    - '#9b4846'
    - '#3a191b'
    - '#ed977d'
  brandStrength: 0.6536431177519262
  lightness: 0.1905819484964013
  saturation: 0.10313550080172718
  rhythmicContrast: 0.5
purpose: []
